### ISSUE TITLE
Any plans to support it for Angular 7?

### ISSUE THREAD

**Issue by kent08ian** [atularen/ngx-monaco-editor#83]

**Comment by pharindoko** [comment]
I tested it. Seems to work with Angular 7. Can you confirm this ?

**Comment by kent08ian** [comment]
Works great! Already tested it on latest Angular 7. but do have any plans to support latest monaco editor v0.15.6? :)

**Comment by jesusvallez** [comment]
Could you explain how i can run ngx-monaco-editor on latest Angular?

**Comment by kent08ian** [comment]
Closing this one since its already working in Angular 7

**Comment by jesusvallez** [comment]
```"assets": [
        { "glob": "**/*", "input": "../node_modules/ngx-monaco-editor/assets/monaco", "output": "./assets/monaco/" }
      ],```

this is not working in Angular 7

**Comment by vasiltabakov** [comment]
I'm having an issue with an Angular 7 project, it _might_ be because of the Angular version. When the language is css I get the following error in the console:
![image](https://user-images.githubusercontent.com/1178309/49522788-1e891400-f8b1-11e8-98a6-9537cb6d015f.png)

Anyone help

@jesusvallez isn't node_modules in the same folder as angular.json?
This works for me:
```
{
                "glob": "**/*",
                "input": "node_modules/ngx-monaco-editor/assets/monaco",
                "output": "./assets/monaco/"
}
```

No **`../`** before node_modules

**Comment by shaharyar123** [comment]
@mhintzke13  mine was also not working on Angular 7, until I changed the config in angular.json
````
 "glob": "**/*", 
  "input": "../node_modules/ngx-monaco-editor/assets/monaco", 
  "output": "./assets/monaco/"
````
to 
````
  "glob": "**/*",
    "input": "node_modules/ngx-monaco-editor/assets/monaco",
     output": "./assets/monaco/"
````
try it.
